using UnityEngine;
using System.Collections.Generic;

public class NodeFace
{
    public enum Name 
    {
        Ceilling,
        Floor,
        Wall,
        Path,
        StaircaseEnd,
        StaircaseTop,
        PathOpen,
        None
    }

    public Name name;
}

[System.Serializable]
public class NodeFaceHorizontal : NodeFace
{
    public enum Type
    {
        None,
        Flipped,
        Original
    }

    public bool symmetry;
    public Type type;
}

[System.Serializable]
public class NodeFaceVertical : NodeFace
{
    public bool invariantRotation;
    [HideInInspector] public int rotationIndex; // Set automatically when autogenerated tiles are rotated and the above value is false
}

[CreateAssetMenu(fileName = "Node", menuName = "WFC/Node")]
public class NodeData : ScriptableObject
{
    public GameObject Prefab;
    public int Weight;
    [HideInInspector] public int ClockwiseRotationSteps; // Set automatically as the tile is rotated

    public NodeFaceVertical Up;
    public NodeFaceVertical Down;
    public NodeFaceHorizontal Left;
    public NodeFaceHorizontal Right;
    public NodeFaceHorizontal Front;
    public NodeFaceHorizontal Back;
}

public class PathNodeData {
    public NodeFace.Name Up = NodeFace.Name.None;
    public NodeFace.Name Down = NodeFace.Name.None;
    public NodeFace.Name Left = NodeFace.Name.None;
    public NodeFace.Name Right = NodeFace.Name.None;
    public NodeFace.Name Front = NodeFace.Name.None;
    public NodeFace.Name Back = NodeFace.Name.None;
}