using UnityEngine;
using System.Linq;
using System.Collections.Generic;

public class NodeFace
{
    public enum Name 
    {
        Ceilling,
        Floor,
        Wall,
        Path,
        StaircaseEnd,
        StaircaseTop,
        PathOpen,
        None
    }

    public Name name;
}

[System.Serializable]
public class NodeFaceHorizontal : NodeFace
{
    public enum Type
    {
        None,
        Flipped,
        Original
    }

    public bool symmetry;
    public Type type;
}

[System.Serializable]
public class NodeFaceVertical : NodeFace
{
    public bool invariantRotation;
    [HideInInspector] public int rotationIndex; // Set automatically when autogenerated tiles are rotated and the above value is false
}

[CreateAssetMenu(fileName = "Node", menuName = "WFC/Node")]
public class Node : ScriptableObject
{
    [System.Flags]
    public enum NodeType
    {
        Corner,
        Corridor,
        Deadend,
        Intersection,
        Junction,
        Staircase
    };

    [System.Flags]
    public enum EnvironmentType
    {
        Objective,
        Study,
        Cellar,
        Garden
    };
    
    public GameObject Prefab;
    public int Weight;
    public bool IsStairPiece;
    public bool CanHaveObjective = false;
    public bool IsDeadEnd = false;
    public bool AllowBeamSpawn = false;
    public NodeType nodeType;
    public EnvironmentType environmentType;
    [HideInInspector] public int ClockwiseRotationSteps; // Set automatically as the tile is rotated

    public NodeFaceVertical Up;
    public NodeFaceVertical Down;
    public NodeFaceHorizontal Left;
    public NodeFaceHorizontal Right;
    public NodeFaceHorizontal Front;
    public NodeFaceHorizontal Back;

    public List<Prop> exceptionsProps;

    public void SetRotation(float rotation)
    {
        if(Prefab != null) Prefab.transform.rotation = Quaternion.Euler(new Vector3(0, rotation, 0));
    }


    // Check if the node can be rotated based on if it has a positive weight and are not symmetrical all the way around
    public bool ShouldRotate()
    {
        return ((Left.type != NodeFaceHorizontal.Type.None 
            || Right.type != NodeFaceHorizontal.Type.None
            || Front.type != NodeFaceHorizontal.Type.None
            || Back.type != NodeFaceHorizontal.Type.None
            || new List<NodeFace.Name>{ Back.name, Right.name, Front.name, Left.name }.Distinct().Skip(1).Any())
            && Weight > 0);
    }

    // Check if this node is symmetrical on two sides
    public bool IsBilateralSymmetric()
    {
        return (Right.name == Left.name 
             && Back.name == Front.name 
             && Right.name != Back.name);
    }

    public void Rotate(int amount)
    {
        if (amount == 0) return;

        amount %= 4;
        RotateVerticalFaces(amount);
        RotateHorizontalFaces(amount);
    }

    private void RotateVerticalFaces(int amount)
    {
        foreach (NodeFaceVertical face in new NodeFaceVertical[]{ Up, Down })
            if(!face.invariantRotation)
                face.rotationIndex = amount;
    }

    private void RotateHorizontalFaces(int amount)
    {
        NodeFaceHorizontal left = Left;
        NodeFaceHorizontal right = Right;
        NodeFaceHorizontal front = Front;
        NodeFaceHorizontal back = Back;

        switch(amount)
        {
            case 1: // 90 degrees
                Back = right;
                Right = front;
                Front = left;
                Left = back;
                break;
            case 2: // 180 degrees
                Back = front;
                Right = left;
                Front = back;
                Left = right;
                break;
            case 3: // 270 degrees
                Back = left;
                Right = back;
                Front = right;
                Left = front;
                break;            
        }
    }

    public (Prop, int) GetRandomPropCDF(PropPlacementType placementType)
    {
        List<Prop> props = new List<Prop>(AssetManager.LoadProps(placementType).Where((Prop p) => !exceptionsProps.Contains(p)));

        if(props.Count <= 0) return (null, 0);

        props.RemoveAll((p) => p.SpawnChance == 0.0f || 
            !p.CompareNode(p.NodeTypeToSpawnIn, this.nodeType) || 
            !p.CompareNode(p.EnvironmentTypeToSpawnIn, this.environmentType));
        props.Sort((x, y) => x.SpawnChance.CompareTo(y.SpawnChance));

        int count = props.Count;

        if(count <= 0) 
        {
            Debug.Log($"Null");
            return (null, 0);
        }

        float totalProbability = 0;

        Prop[] cdf = new Prop[count];

        for (int i = 0; i < count; i++)
        {
            totalProbability += props[i].SpawnChance;

            Prop p = new Prop(props[i]);
            cdf[i] = p;
        }

        for (int i = 0; i < count; i++)
            cdf[i].SpawnChance /= totalProbability;

        float rand = UnityEngine.Random.value;

        int low = 0;
        int high = cdf.Length - 1;

        while (low < high)
        {
            int mid = (low + high) / 2;

            if (cdf[mid].SpawnChance >= rand)
                high = mid;
            else 
                low = mid + 1;
        }

        return (cdf[low], count);
    }
}

public class PathNodeData {
    public NodeFace.Name Up = NodeFace.Name.None;
    public NodeFace.Name Down = NodeFace.Name.None;
    public NodeFace.Name Left = NodeFace.Name.None;
    public NodeFace.Name Right = NodeFace.Name.None;
    public NodeFace.Name Front = NodeFace.Name.None;
    public NodeFace.Name Back = NodeFace.Name.None;
}